/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/puzzle.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/puzzle.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.464, 0.143, 4.09]} rotation={[0, -0.92, 0]} scale={0.073}>
        <mesh geometry={nodes.Cylinder018_Cylinder007.geometry} material={materials.Car} />
        <mesh geometry={nodes.Cylinder018_Cylinder007_1.geometry} material={materials.Windshield} />
      </group>
      <mesh geometry={nodes.Ice_Cream_Truck.geometry} material={materials['Ice Cream Truck Material.001']} position={[-0.157, 0.119, 4.189]} rotation={[0, -0.527, 0]} scale={0.469} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[1.092, 0.81, 2.531]} scale={[1.165, 1, 1]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.002']} position={[1.006, 0.771, 9.454]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.006']} position={[0.602, 0.84, 9.285]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.007']} position={[0.962, 0.763, 2.262]} rotation={[Math.PI / 2, 0, 0]} scale={0.731} />
    </group>
  )
}

useGLTF.preload('/puzzle.glb')
