/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/rohitoffice.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from "gsap";
import { useFrame } from '@react-three/fiber';
import * as THREE from "three";
import { MeshPhysicalMaterial } from 'three';
import { useEnvironment } from '@react-three/drei';

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Office(props) {
  const { nodes, materials } = useGLTF('./models/rohitoffice.glb')
  const ref = useRef();
  const tl = useRef();
  const libraryRef = useRef();
  const atticRef = useRef();

  const scroll = useScroll();
  const envMap = useEnvironment({ preset: "city" });



  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0.553, 3.119, -3.518]} scale={0.129}>
        <mesh geometry={nodes.Bar_mesh_1001.geometry} material={materials['Bar_A_mat.001']} />
        <mesh geometry={nodes.Bar_mesh_1001_1.geometry} material={materials['Bar_B_mat.001']} />
      </group>
      <group position={[-0.327, 1.276, 0.678]} scale={0.739}>
        <mesh geometry={nodes._2_floor_factory_1002.geometry} material={materials['ID20.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_1.geometry} material={materials['ID68.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_2.geometry} material={materials['JoinedMaterial_#27.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_3.geometry} material={materials['ID6.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_4.geometry} material={materials['JoinedMaterial_#32.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_5.geometry} material={materials['ID34.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_6.geometry} material={materials['ID464.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_7.geometry} material={materials['ID144.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_8.geometry} material={materials['ID191.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_9.geometry} material={materials['ID199.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_10.geometry} material={materials['ID258.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_11.geometry} material={materials['ID278.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_12.geometry} material={materials['ID286.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_13.geometry} material={materials['ID119.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_14.geometry} material={materials['ID578.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_15.geometry} material={materials['ID765.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_16.geometry} material={materials['ID775.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_17.geometry} material={materials['ID791.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_18.geometry} material={materials['ID841.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_19.geometry} material={materials['ID885.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_20.geometry} material={materials['ID909.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_21.geometry} material={materials['ID925.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_22.geometry} material={materials['ID1112.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_23.geometry} material={materials['ID1121.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_24.geometry} material={materials['ID1175.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_25.geometry} material={materials['ID1184.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_26.geometry} material={materials['JoinedMaterial_#11.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_27.geometry} material={materials['ID105.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_28.geometry} material={materials['ID127.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_29.geometry} material={materials['ID446.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_30.geometry} material={materials['ID422.002']} />
        <mesh geometry={nodes._2_floor_factory_1002_31.geometry} material={materials['ID430.002']} />
      </group>
      <group position={[3.79, -0.756, 0.678]} scale={0.739}>
        <mesh geometry={nodes._2_floor_factory_1003.geometry} material={materials['ID20.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_1.geometry} material={materials['ID68.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_2.geometry} material={materials['JoinedMaterial_#27.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_3.geometry} material={materials['ID6.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_4.geometry} material={materials['JoinedMaterial_#32.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_5.geometry} material={materials['ID34.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_6.geometry} material={materials['ID464.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_7.geometry} material={materials['ID144.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_8.geometry} material={materials['ID191.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_9.geometry} material={materials['ID199.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_10.geometry} material={materials['ID258.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_11.geometry} material={materials['ID278.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_12.geometry} material={materials['ID286.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_13.geometry} material={materials['ID119.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_14.geometry} material={materials['ID578.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_15.geometry} material={materials['ID765.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_16.geometry} material={materials['ID775.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_17.geometry} material={materials['ID791.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_18.geometry} material={materials['ID841.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_19.geometry} material={materials['ID885.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_20.geometry} material={materials['ID909.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_21.geometry} material={materials['ID925.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_22.geometry} material={materials['ID1112.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_23.geometry} material={materials['ID1121.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_24.geometry} material={materials['ID1175.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_25.geometry} material={materials['ID1184.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_26.geometry} material={materials['JoinedMaterial_#11.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_27.geometry} material={materials['ID105.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_28.geometry} material={materials['ID127.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_29.geometry} material={materials['ID446.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_30.geometry} material={materials['ID422.003']} />
        <mesh geometry={nodes._2_floor_factory_1003_31.geometry} material={materials['ID430.003']} />
      </group>
      <mesh geometry={nodes.Cube.geometry} position={[0.551, 3.144, -3.336]} scale={-0.162}>
        <meshPhysicalMaterial
          color="white"
          roughness={0.1} // Slight roughness helps with reflections
          metalness={0.5} // Reduce metalness to allow some shading
          transmission={0.2}
          transparent
          thickness={0.5}
        />

      </mesh>





    </group>
  )
}

useGLTF.preload('./models/rohitoffice.glb')
